In [29]:
import pandas as pd

In [30]:
#########
kospi2018=pd.read_csv('./job/2018코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2017=pd.read_csv('./job/2017코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2016=pd.read_csv('./job/2016코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2015=pd.read_csv('./job/2015코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2014=pd.read_csv('./job/2014코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2013=pd.read_csv('./job/2013코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2012=pd.read_csv('./job/2012코스피업종분류.csv',encoding='euc-kr',index_col='종목명')
kospi2011=pd.read_csv('./job/2011코스피업종분류.csv',encoding='euc-kr',index_col='종목명')

##########
kospi2011_list=kospi2011.index.tolist()
kospi2012_list=kospi2012.index.tolist()
kospi2013_list=kospi2013.index.tolist()
kospi2014_list=kospi2014.index.tolist()
kospi2015_list=kospi2015.index.tolist()
kospi2016_list=kospi2016.index.tolist()
kospi2017_list=kospi2017.index.tolist()
kospi2018_list=kospi2018.index.tolist()

##########
df_11=pd.read_csv('./ESG_csv/2011.csv',encoding='euc-kr').fillna('C')
df_12=pd.read_csv('./ESG_csv/2012.csv',encoding='euc-kr').fillna('C')
df_13=pd.read_csv('./ESG_csv/2013.csv',encoding='euc-kr').fillna('C')
df_14=pd.read_csv('./ESG_csv/2014.csv',encoding='euc-kr').fillna('C')
df_15=pd.read_csv('./ESG_csv/2015.csv',encoding='euc-kr').fillna('C')
df_16=pd.read_csv('./ESG_csv/2016.csv',encoding='euc-kr').fillna('C')
df_17=pd.read_csv('./ESG_csv/2017.csv',encoding='euc-kr').fillna('C')
df_18=pd.read_csv('./ESG_csv/2018.csv',encoding='euc-kr').fillna('C')

##########
df_11.set_index('종목명',drop=True,inplace=True)
df_12.set_index('종목명',drop=True,inplace=True)
df_13.set_index('종목명',drop=True,inplace=True)
df_14.set_index('종목명',drop=True,inplace=True)
df_15.set_index('종목명',drop=True,inplace=True)
df_16.set_index('종목명',drop=True,inplace=True)
df_17.set_index('종목명',drop=True,inplace=True)
df_18.set_index('종목명',drop=True,inplace=True)

##########
name_11=df_11.index.to_list()
name_12=df_12.index.to_list()
name_13=df_13.index.to_list()
name_14=df_14.index.to_list()
name_15=df_15.index.to_list()
name_16=df_16.index.to_list()
name_17=df_17.index.to_list()
name_18=df_18.index.to_list()

## 2011

In [31]:
set1=set(kospi2011_list)
set2=set(name_11)
common_values = list(set1 & set2)

list1=df_11.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2011.loc[common_values].sort_index()[['업종명']]
df_11_add_job=pd.concat([list1,list2],axis=1)
df_11_add_job

       ESG 통합등급 2011_E 2011_S 2011_G  평가연도    업종명
종목명
BYC         B이하      B    B이하    B이하  2011   섬유의복
CJ          B이하     B+    B이하      C  2011   서비스업
CJ CGV      B이하      B    B이하      C  2011   서비스업
CJ씨푸드         C      C      C      C  2011   음식료품
CJ제일제당       B+     B+     B+      A  2011   음식료품
...         ...    ...    ...    ...   ...    ...
후성          B이하      C    B이하    B이하  2011     화학
휴스틸           C      B      C    B이하  2011   철강금속
휴켐스         B이하     B+    B이하     B+  2011     화학
흥국화재        B이하      C    B이하      C  2011     보험
흥아해운        B이하      B    B이하      C  2011  운수창고업

[506 rows x 6 columns]

## 2012

In [32]:
set1=set(kospi2012_list)
set2=set(name_12)
common_values = list(set1 & set2)

list1=df_12.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2012.loc[common_values].sort_index()[['업종명']]
df_12_add_job=pd.concat([list1,list2],axis=1)
df_12_add_job

       ESG 통합등급 2012_E 2012_S 2012_G  평가연도    업종명
종목명
AK홀딩스       B이하      C    B이하     B+  2012     화학
BYC         B이하      C    B이하    B이하  2012   섬유의복
CJ          B이하      B    B이하    B이하  2012   서비스업
CJ CGV      B이하      B    B이하    B이하  2012   서비스업
CJ대한통운      B이하      B     B+    B이하  2012  운수창고업
...         ...    ...    ...    ...   ...    ...
휠라코리아       B이하      B    B이하    B이하  2012    유통업
휴스틸         B이하      B    B이하     B+  2012   철강금속
휴켐스          B+      B     B+     B+  2012     화학
흥국화재        B이하      B    B이하    B이하  2012     보험
흥아해운        B이하      B    B이하    B이하  2012  운수창고업

[552 rows x 6 columns]

## 2013

In [33]:
set1=set(kospi2013_list)
set2=set(name_13)
common_values = list(set1 & set2)

list1=df_13.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2013.loc[common_values].sort_index()[['업종명']]
df_13_add_job=pd.concat([list1,list2],axis=1)
df_13_add_job

       ESG 통합등급 2013_E 2013_S 2013_G  평가연도    업종명
종목명
AK홀딩스       B이하      C    B이하    B이하  2013   서비스업
BYC         B이하      B    B이하    B이하  2013   섬유의복
CJ           B+      B      A    B이하  2013   서비스업
CJ CGV      B이하      B    B이하    B이하  2013   서비스업
CJ대한통운       B+     B+      A     B+  2013  운수창고업
...         ...    ...    ...    ...   ...    ...
휠라코리아       B이하      B    B이하    B이하  2013    유통업
휴스틸         B이하      B    B이하    B이하  2013   철강금속
휴켐스          B+      B     B+     B+  2013     화학
흥국화재        B이하      B    B이하    B이하  2013     보험
흥아해운        B이하      B    B이하    B이하  2013  운수창고업

[557 rows x 6 columns]

## 2014

In [34]:
set1=set(kospi2014_list)
set2=set(name_14)
common_values = list(set1 & set2)

list1=df_14.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2014.loc[common_values].sort_index()[['업종명']]
df_14_add_job=pd.concat([list1,list2],axis=1)
df_14_add_job

       ESG 통합등급 2014_E 2014_S 2014_G  평가연도    업종명
종목명
AJ렌터카       B이하      C    B이하    B이하  2014   서비스업
AK홀딩스       B이하      C    B이하    B이하  2014   서비스업
BYC         B이하      C    B이하    B이하  2014   섬유의복
CJ           B+      B      A     B+  2014   서비스업
CJ CGV      B이하      C     B+    B이하  2014   서비스업
...         ...    ...    ...    ...   ...    ...
휴비스         B이하      C    B이하    B이하  2014     화학
휴스틸         B이하      B    B이하     B+  2014   철강금속
휴켐스          B+      B     B+     B+  2014     화학
흥국화재        B이하      B    B이하    B이하  2014     보험
흥아해운        B이하      B    B이하    B이하  2014  운수창고업

[577 rows x 6 columns]

## 2015년

In [35]:
set1=set(kospi2015_list)
set2=set(name_15)
common_values = list(set1 & set2)

list1=df_15.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2015.loc[common_values].sort_index()[['업종명']]
df_15_add_job=pd.concat([list1,list2],axis=1)
df_15_add_job

        ESG 통합등급 2015_E 2015_S 2015_G  평가연도    업종명
종목명
AJ렌터카        B이하      C    B이하    B이하  2015   서비스업
AK홀딩스        B이하      C    B이하    B이하  2015   서비스업
BNK금융지주        A     A+      A    B이하  2015   기타금융
BYC          B이하      C    B이하    B이하  2015   섬유의복
CJ            B+      B      A     B+  2015   서비스업
...          ...    ...    ...    ...   ...    ...
휴비스          B이하      C    B이하    B이하  2015     화학
휴스틸          B이하      B    B이하     B+  2015   철강금속
휴켐스          B이하      B    B이하     B+  2015     화학
흥국화재         B이하     B+    B이하    B이하  2015     보험
흥아해운         B이하      B    B이하    B이하  2015  운수창고업

[600 rows x 6 columns]

## 2016년

In [36]:
set1=set(kospi2016_list)
set2=set(name_16)
common_values = list(set1 & set2)

list1=df_16.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2016.loc[common_values].sort_index()[['업종명']]
df_16_add_job=pd.concat([list1,list2],axis=1)
df_16_add_job

        ESG 통합등급 2016_E 2016_S 2016_G  평가연도    업종명
종목명
AJ네트웍스       B이하      C    B이하    B이하  2016   서비스업
AJ렌터카        B이하      C    B이하    B이하  2016   서비스업
AK홀딩스        B이하      B    B이하    B이하  2016   서비스업
BNK금융지주        A     A+     B+    B이하  2016   기타금융
BYC          B이하      C    B이하    B이하  2016   섬유의복
...          ...    ...    ...    ...   ...    ...
휴비스           B+      B     B+     B+  2016     화학
휴스틸          B이하      B    B이하     B+  2016   철강금속
휴켐스           B+      B     B+      A  2016     화학
흥국화재          B+     A+    B이하    B이하  2016     보험
흥아해운         B이하      C    B이하    B이하  2016  운수창고업

[627 rows x 6 columns]

## 2017년

In [37]:
set1=set(kospi2017_list)
set2=set(name_17)
common_values = list(set1 & set2)

list1=df_17.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2017.loc[common_values].sort_index()[['업종명']]
df_17_add_job=pd.concat([list1,list2],axis=1)
df_17_add_job

        ESG 통합등급 2017_E 2017_S 2017_G  평가연도    업종명
종목명
AJ네트웍스       B이하      B    B이하    B이하  2017   서비스업
AJ렌터카        B이하      C    B이하    B이하  2017   서비스업
AK홀딩스        B이하      B    B이하    B이하  2017   기타금융
BNK금융지주       B+      B      A     B+  2017   기타금융
BYC          B이하      B    B이하    B이하  2017   섬유의복
...          ...    ...    ...    ...   ...    ...
휴비스           B+      B      A     B+  2017     화학
휴스틸          B이하      B    B이하    B이하  2017   철강금속
휴켐스           B+      B     B+     B+  2017     화학
흥국화재          B+      A    B이하    B이하  2017     보험
흥아해운         B이하      B    B이하    B이하  2017  운수창고업

[663 rows x 6 columns]

## 2018년

In [38]:
set1=set(kospi2018_list)
set2=set(name_18)
common_values = list(set1 & set2)

list1=df_18.loc[common_values]
list1=list1.loc[~list1.index.duplicated()]
list1.sort_index(inplace=True)

list2=kospi2018.loc[common_values].sort_index()[['업종명']]
df_18_add_job=pd.concat([list1,list2],axis=1)
df_18_add_job

        ESG 통합등급 2018_E 2018_S 2018_G  평가연도    업종명
종목명
AJ네트웍스       B이하      C    B이하    B이하  2018   서비스업
AJ렌터카        B이하      B    B이하     B+  2018   서비스업
AK홀딩스        B이하      C    B이하    B이하  2018   기타금융
BGF            C      B      C      C  2018   기타금융
BNK금융지주       B+  B+ 이하     B+    B이하  2018   기타금융
...          ...    ...    ...    ...   ...    ...
휴비스           B+     B+     B+     B+  2018     화학
휴스틸          B이하      B    B이하    B이하  2018   철강금속
휴켐스          B이하      B    B이하     B+  2018     화학
흥국화재         B이하  B+ 이하    B이하    B이하  2018     보험
흥아해운         B이하      C    B이하    B이하  2018  운수창고업

[680 rows x 6 columns]

In [42]:
#df_11_add_job.to_csv('./OO_origin/Origin_11.csv')
#df_12_add_job.to_csv('./OO_origin/Origin_12.csv')
#df_13_add_job.to_csv('./OO_origin/Origin_13.csv')
#df_14_add_job.to_csv('./OO_origin/Origin_14.csv')
#df_15_add_job.to_csv('./OO_origin/Origin_15.csv')
#df_16_add_job.to_csv('./OO_origin/Origin_16.csv')
#df_17_add_job.to_csv('./OO_origin/Origin_17.csv')
#df_18_add_job.to_csv('./OO_origin/Origin_18.csv')